name: build

on: [push, pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: build docs
        run: |
          python -m pip install mkdocs-material
          mkdocs build -s -d /tmp/neodb-docs
